### ISSUE TITLE
Algorithm identifier table KDF columns contain hash algorithms

### ISSUE THREAD

**Issue by bluegate010** [lamps-wg/draft-composite-kem#73]
It is a bit confusing on first read to see hash algorithms in the section 5 & 6.1 tables' KDF columns (SHA3-256, SHA3-384, SHA3-512).

From reading footnotes under the table in section 6.1, it appears those shortnames refer to [this](https://datatracker.ietf.org/doc/html/draft-ietf-lamps-cms-sha3-hash-01#name-hkdf-with-sha3) draft RFC. It might be clearer to prepend the shortnames in the section 6.1 table with HKDF-* (HKDF-SHA3-256 etc).

It is not clear what the hash algorithms in table 5's KDF column refer to.

**Comment by ounsworth** [comment]
Hi @bluegate010 Thank you for the comment.

This has been adjusted a bit in the most recent version. We now use either `HKDF-SHA256/256` or `SHA3-256` for the internal KEM combiner KDF -- note that there is no cryptographic reason why we need HKDF-SHA3 because a single iteration of SHA3 by already has the necessary DualPRF properties (but SHA2 does not, hence needing the HMAC / HKDF wrapper).

For the KDF used as the CMS KEMRecipientInfo layer we need a proper KDF, not for security property reasons, but because it needs to be variable-length output, so here we use either HKDF-SHA2 or KMAC.


Please see the updated version here (which will be posted to IETF Datatracker on Oct 21). Please let me know if this is still unclear. I am going to close this ticket for now, but feel free to re-open it.

https://lamps-wg.github.io/draft-composite-kem/draft-ietf-lamps-pq-composite-kem.html
